/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export enum MessageType {
  Text,
  Image,
  Code,
  File,
}

export type MessageTypeArgs = MessageType;

export function getMessageTypeEncoder(): Encoder<MessageTypeArgs> {
  return getEnumEncoder(MessageType);
}

export function getMessageTypeDecoder(): Decoder<MessageType> {
  return getEnumDecoder(MessageType);
}

export function getMessageTypeCodec(): Codec<MessageTypeArgs, MessageType> {
  return combineCodec(getMessageTypeEncoder(), getMessageTypeDecoder());
}
