/**
 * This code was GENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  type Address,
  type IAccountMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/web3.js';
import {
  combineCodec,
  getArrayDecoder,
  getArrayEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  transformEncoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/codecs';

export const PURCHASE_SERVICE_DISCRIMINATOR = new Uint8Array([
  201, 156, 88, 123, 45, 92, 200, 77,
]);

export function getPurchaseServiceDiscriminatorBytes() {
  return PURCHASE_SERVICE_DISCRIMINATOR.slice();
}

export type PurchaseServiceInstruction<
  TProgram extends string = 'PodAI111111111111111111111111111111111111111',
  TAccountServicePurchase extends string | IAccountMeta<string> = string,
  TAccountServiceListing extends string | IAccountMeta<string> = string,
  TAccountBuyer extends string | IAccountMeta<string> = string,
  TAccountSystemProgram extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountServicePurchase extends string
        ? WritableAccount<TAccountServicePurchase>
        : TAccountServicePurchase,
      TAccountServiceListing extends string
        ? WritableAccount<TAccountServiceListing>
        : TAccountServiceListing,
      TAccountBuyer extends string
        ? WritableSignerAccount<TAccountBuyer>
        : TAccountBuyer,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type PurchaseServiceInstructionData = {
  discriminator: ReadonlyUint8Array;
  purchaseData: ServicePurchaseData;
};

export type ServicePurchaseData = {
  listingId: bigint;
  quantity: number;
  requirements: string[];
  customInstructions: string;
  deadline: bigint;
};

export type PurchaseServiceInstructionDataArgs = {
  purchaseData: ServicePurchaseDataArgs;
};

export type ServicePurchaseDataArgs = {
  listingId: number | bigint;
  quantity: number;
  requirements: string[];
  customInstructions: string;
  deadline: number | bigint;
};

export function getPurchaseServiceInstructionDataEncoder(): Encoder<PurchaseServiceInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', getPurchaseServiceDiscriminatorBytes()],
      ['purchaseData', getServicePurchaseDataEncoder()],
    ]),
    (value) => ({ ...value, discriminator: getPurchaseServiceDiscriminatorBytes() })
  );
}

export function getPurchaseServiceInstructionDataDecoder(): Decoder<PurchaseServiceInstructionData> {
  return getStructDecoder([
    ['discriminator', getPurchaseServiceDiscriminatorBytes()],
    ['purchaseData', getServicePurchaseDataDecoder()],
  ]);
}

export function getPurchaseServiceInstructionDataCodec(): Codec<
  PurchaseServiceInstructionDataArgs,
  PurchaseServiceInstructionData
> {
  return combineCodec(
    getPurchaseServiceInstructionDataEncoder(),
    getPurchaseServiceInstructionDataDecoder()
  );
}

export function getServicePurchaseDataEncoder(): Encoder<ServicePurchaseDataArgs> {
  return getStructEncoder([
    ['listingId', getU64Encoder()],
    ['quantity', getU32Encoder()],
    ['requirements', getArrayEncoder(getUtf8Encoder())],
    ['customInstructions', getUtf8Encoder()],
    ['deadline', getU64Encoder()],
  ]);
}

export function getServicePurchaseDataDecoder(): Decoder<ServicePurchaseData> {
  return getStructDecoder([
    ['listingId', getU64Decoder()],
    ['quantity', getU32Decoder()],
    ['requirements', getArrayDecoder(getUtf8Decoder())],
    ['customInstructions', getUtf8Decoder()],
    ['deadline', getU64Decoder()],
  ]);
}

export function getServicePurchaseDataCodec(): Codec<ServicePurchaseDataArgs, ServicePurchaseData> {
  return combineCodec(getServicePurchaseDataEncoder(), getServicePurchaseDataDecoder());
}

export type PurchaseServiceInput<
  TAccountServicePurchase extends string = string,
  TAccountServiceListing extends string = string,
  TAccountBuyer extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  servicePurchase: Address<TAccountServicePurchase>;
  serviceListing: Address<TAccountServiceListing>;
  buyer: Address<TAccountBuyer>;
  systemProgram?: Address<TAccountSystemProgram>;
  purchaseData: ServicePurchaseDataArgs;
};

export function getPurchaseServiceInstruction<
  TAccountServicePurchase extends string,
  TAccountServiceListing extends string,
  TAccountBuyer extends string,
  TAccountSystemProgram extends string,
>(
  input: PurchaseServiceInput<TAccountServicePurchase, TAccountServiceListing, TAccountBuyer, TAccountSystemProgram>
): PurchaseServiceInstruction<
  'PodAI111111111111111111111111111111111111111',
  TAccountServicePurchase,
  TAccountServiceListing,
  TAccountBuyer,
  TAccountSystemProgram
> {
  // Program ID
  const programId = 'PodAI111111111111111111111111111111111111111' as Address<'PodAI111111111111111111111111111111111111111'>;

  // Accounts
  const accounts: PurchaseServiceInstruction<
    'PodAI111111111111111111111111111111111111111',
    TAccountServicePurchase,
    TAccountServiceListing,
    TAccountBuyer,
    TAccountSystemProgram
  >['accounts'] = [
    {
      address: input.servicePurchase,
      role: 'writable',
    },
    {
      address: input.serviceListing,
      role: 'writable',
    },
    {
      address: input.buyer,
      role: 'writable',
      signer: true,
    },
    {
      address: input.systemProgram ?? ('11111111111111111111111111111111' as Address<TAccountSystemProgram>),
      role: 'readonly',
    },
  ];

  // Instruction data
  const args = { purchaseData: input.purchaseData };
  const data = getPurchaseServiceInstructionDataEncoder().encode(args);

  return {
    programId,
    accounts,
    data,
  };
}

export type ParsedPurchaseServiceInstruction<
  TProgram extends string = 'PodAI111111111111111111111111111111111111111',
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programId: Address<TProgram>;
  accounts: {
    servicePurchase: TAccountMetas[0];
    serviceListing: TAccountMetas[1];
    buyer: TAccountMetas[2];
    systemProgram: TAccountMetas[3];
  };
  data: PurchaseServiceInstructionData;
};

export function parsePurchaseServiceInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> & IInstructionWithAccounts<TAccountMetas> & IInstructionWithData<Uint8Array>
): ParsedPurchaseServiceInstruction<TProgram, TAccountMetas> {
  return {
    programId: instruction.programId,
    accounts: {
      servicePurchase: instruction.accounts[0]!,
      serviceListing: instruction.accounts[1]!,
      buyer: instruction.accounts[2]!,
      systemProgram: instruction.accounts[3]!,
    },
    data: getPurchaseServiceInstructionDataDecoder().decode(instruction.data),
  };
}

export async function getPurchaseServiceInstructionAsync<
  TAccountServicePurchase extends string,
  TAccountServiceListing extends string,
  TAccountBuyer extends string,
  TAccountSystemProgram extends string,
>(
  input: PurchaseServiceInput<TAccountServicePurchase, TAccountServiceListing, TAccountBuyer, TAccountSystemProgram>
): Promise<PurchaseServiceInstruction<
  'PodAI111111111111111111111111111111111111111',
  TAccountServicePurchase,
  TAccountServiceListing,
  TAccountBuyer,
  TAccountSystemProgram
>> {
  // NOTE: This instruction does not need any account resolution
  return getPurchaseServiceInstruction(input);
} 